// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.28.2
// source: champions.proto

package jstreams_server

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ChampionsService_GetChampions_FullMethodName = "/champions.ChampionsService/GetChampions"
)

// ChampionsServiceClient is the client API for ChampionsService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ChampionsServiceClient interface {
	GetChampions(ctx context.Context, in *GetChampionsRequest, opts ...grpc.CallOption) (*GetChampionsResponse, error)
}

type championsServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewChampionsServiceClient(cc grpc.ClientConnInterface) ChampionsServiceClient {
	return &championsServiceClient{cc}
}

func (c *championsServiceClient) GetChampions(ctx context.Context, in *GetChampionsRequest, opts ...grpc.CallOption) (*GetChampionsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetChampionsResponse)
	err := c.cc.Invoke(ctx, ChampionsService_GetChampions_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ChampionsServiceServer is the server API for ChampionsService service.
// All implementations must embed UnimplementedChampionsServiceServer
// for forward compatibility.
type ChampionsServiceServer interface {
	GetChampions(context.Context, *GetChampionsRequest) (*GetChampionsResponse, error)
	mustEmbedUnimplementedChampionsServiceServer()
}

// UnimplementedChampionsServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedChampionsServiceServer struct{}

func (UnimplementedChampionsServiceServer) GetChampions(context.Context, *GetChampionsRequest) (*GetChampionsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetChampions not implemented")
}
func (UnimplementedChampionsServiceServer) mustEmbedUnimplementedChampionsServiceServer() {}
func (UnimplementedChampionsServiceServer) testEmbeddedByValue()                          {}

// UnsafeChampionsServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ChampionsServiceServer will
// result in compilation errors.
type UnsafeChampionsServiceServer interface {
	mustEmbedUnimplementedChampionsServiceServer()
}

func RegisterChampionsServiceServer(s grpc.ServiceRegistrar, srv ChampionsServiceServer) {
	// If the following call pancis, it indicates UnimplementedChampionsServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ChampionsService_ServiceDesc, srv)
}

func _ChampionsService_GetChampions_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetChampionsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChampionsServiceServer).GetChampions(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ChampionsService_GetChampions_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChampionsServiceServer).GetChampions(ctx, req.(*GetChampionsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ChampionsService_ServiceDesc is the grpc.ServiceDesc for ChampionsService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ChampionsService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "champions.ChampionsService",
	HandlerType: (*ChampionsServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetChampions",
			Handler:    _ChampionsService_GetChampions_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "champions.proto",
}
