// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.28.2
// source: entries.proto

package jstreams_server

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	EntriesService_GetEntriesBySummoner_FullMethodName = "/entries.EntriesService/GetEntriesBySummoner"
)

// EntriesServiceClient is the client API for EntriesService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type EntriesServiceClient interface {
	GetEntriesBySummoner(ctx context.Context, in *GetEntriesBySummonerRequest, opts ...grpc.CallOption) (*GetEntriesBySummonerResponse, error)
}

type entriesServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewEntriesServiceClient(cc grpc.ClientConnInterface) EntriesServiceClient {
	return &entriesServiceClient{cc}
}

func (c *entriesServiceClient) GetEntriesBySummoner(ctx context.Context, in *GetEntriesBySummonerRequest, opts ...grpc.CallOption) (*GetEntriesBySummonerResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetEntriesBySummonerResponse)
	err := c.cc.Invoke(ctx, EntriesService_GetEntriesBySummoner_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// EntriesServiceServer is the server API for EntriesService service.
// All implementations must embed UnimplementedEntriesServiceServer
// for forward compatibility.
type EntriesServiceServer interface {
	GetEntriesBySummoner(context.Context, *GetEntriesBySummonerRequest) (*GetEntriesBySummonerResponse, error)
	mustEmbedUnimplementedEntriesServiceServer()
}

// UnimplementedEntriesServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedEntriesServiceServer struct{}

func (UnimplementedEntriesServiceServer) GetEntriesBySummoner(context.Context, *GetEntriesBySummonerRequest) (*GetEntriesBySummonerResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetEntriesBySummoner not implemented")
}
func (UnimplementedEntriesServiceServer) mustEmbedUnimplementedEntriesServiceServer() {}
func (UnimplementedEntriesServiceServer) testEmbeddedByValue()                        {}

// UnsafeEntriesServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to EntriesServiceServer will
// result in compilation errors.
type UnsafeEntriesServiceServer interface {
	mustEmbedUnimplementedEntriesServiceServer()
}

func RegisterEntriesServiceServer(s grpc.ServiceRegistrar, srv EntriesServiceServer) {
	// If the following call pancis, it indicates UnimplementedEntriesServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&EntriesService_ServiceDesc, srv)
}

func _EntriesService_GetEntriesBySummoner_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetEntriesBySummonerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EntriesServiceServer).GetEntriesBySummoner(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EntriesService_GetEntriesBySummoner_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EntriesServiceServer).GetEntriesBySummoner(ctx, req.(*GetEntriesBySummonerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// EntriesService_ServiceDesc is the grpc.ServiceDesc for EntriesService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var EntriesService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "entries.EntriesService",
	HandlerType: (*EntriesServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetEntriesBySummoner",
			Handler:    _EntriesService_GetEntriesBySummoner_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "entries.proto",
}
